CREATE TABLE `phone` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`value` VARCHAR(50) NOT NULL,
	`type` VARCHAR(20)  NOT NULL CHECK `type` IN ('HOME','MOBILE','NO_INFORMATION'),
	`comment` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(50) NOT NULL,
	`last_name` VARCHAR(50) NOT NULL,
	`patronymic` VARCHAR(50) NOT NULL,
	`phone_id` BIGINT(20) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`phone_id`) REFERENCES `phone` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;